# -*- coding: utf-8 -*-
"""analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EL23qtY-hne_QpkLUlyqAWUnFuVIyi9O
"""

"""
This module contains analytical functions used to evaluate movie performance
based on financial, popularity, and rating metrics.

Responsibilities:
- Rank movies using different KPIs
- Perform advanced filtering and search queries
- Compare franchise vs standalone movie performance
- Identify the most successful franchises and directors

"""

import pandas as pd


# ----------------------------------------------------------------------
# Ranking Function
# ----------------------------------------------------------------------
def rank_movies(df, metric, top_n=5, ascending=False,
                min_budget=None, min_votes=None):

    temp = df.copy()

    if min_budget is not None:
        temp = temp[temp['budget_musd'] >= min_budget]

    if min_votes is not None:
        temp = temp[temp['vote_count'] >= min_votes]

    return (
        temp[['title', metric]]
        .dropna()
        .sort_values(metric, ascending=ascending)
        .head(top_n)
    )


# ----------------------------------------------------------------------
# 2. Advanced Filtering Queries
# ----------------------------------------------------------------------
def search_bruce_willis_scifi_action(df):
    """
    Find best-rated Science Fiction Action movies starring Bruce Willis.

    Returns movies sorted by vote_average (highest to lowest).
    """
    return (
        df[
            df['genres'].str.contains('Science Fiction', na=False) &
            df['genres'].str.contains('Action', na=False) &
            df['cast'].str.contains('Bruce Willis', na=False)
        ]
        .sort_values('vote_average', ascending=False)
    )


def search_uma_thurman_tarantino(df):
    """
    Find movies starring Uma Thurman and directed by Quentin Tarantino.

    Returns movies sorted by runtime (shortest to longest).
    """
    return (
        df[
            df['cast'].str.contains('Uma Thurman', na=False) &
            (df['director'] == 'Quentin Tarantino')
        ]
        .sort_values('runtime')
    )


# ----------------------------------------------------------------------
# 3. Franchise vs Standalone Movie Performance
# ----------------------------------------------------------------------
def franchise_summary(df):

    return (
        df.groupby('is_franchise')
        .agg(
            mean_revenue=('revenue_musd', 'mean'),
            median_roi=('roi', 'median'),
            mean_budget=('budget_musd', 'mean'),
            mean_popularity=('popularity', 'mean'),
            mean_rating=('vote_average', 'mean')
        )
    )


# ----------------------------------------------------------------------
# 4. Most Successful Movie Franchises
# ----------------------------------------------------------------------
def top_franchises(df):

    return (
        df.dropna(subset=['belongs_to_collection'])
        .groupby('belongs_to_collection')
        .agg(
            movie_count=('id', 'count'),
            total_budget=('budget_musd', 'sum'),
            mean_budget=('budget_musd', 'mean'),
            total_revenue=('revenue_musd', 'sum'),
            mean_revenue=('revenue_musd', 'mean'),
            mean_rating=('vote_average', 'mean')
        )
        .sort_values('total_revenue', ascending=False)
    )


# ----------------------------------------------------------------------
# 5. Most Successful Directors
# ----------------------------------------------------------------------
def top_directors(df):

    return (
        df.dropna(subset=['director'])
        .groupby('director')
        .agg(
            movie_count=('id', 'count'),
            total_revenue=('revenue_musd', 'sum'),
            mean_rating=('vote_average', 'mean')
        )
        .sort_values('total_revenue', ascending=False)
    )