# -*- coding: utf-8 -*-
"""api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-6tE-n52o7NVZT1oVzY-CR-Fu1wASYKq
"""

"""
This module handles API data extraction from The Movie Database (TMDb).

It is responsible for:
- Communicating with the TMDb API
- Fetching movie metadata using predefined movie IDs
- Returning the raw movie data as a Pandas DataFrame

"""

import requests
import pandas as pd

# Base URL for TMDb movie details endpoint
BASE_URL = "https://api.themoviedb.org/3/movie/"

def fetch_movies(movie_ids, api_key):

    # Filter out invalid movie IDs
    valid_ids = [mid for mid in movie_ids if mid != 0]

    # API calls
    responses = []

    for movie_id in valid_ids:
        response = requests.get(
            f"{BASE_URL}{movie_id}",
            params={"api_key": api_key}
        )

        # Ensure request was successful
        if response.status_code == 200:
            responses.append(response.json())

    # Convert list of dictionaries to DataFrame
    return pd.DataFrame(responses)

