# -*- coding: utf-8 -*-
"""cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KF0xPvk18qliAiToD9PZeADxABiWMgSb
"""

"""
This module performs data cleaning and preprocessing on raw movie data
retrieved from the TMDb API.

Responsibilities:
- Remove irrelevant columns
- Extract and flatten JSON-like columns
- Handle missing and unrealistic values
- Convert data types to appropriate formats
- Create budget and revenue metrics in million USD
- Filter valid and complete movie records
- Reorder columns to match the project specification

"""

import numpy as np
import pandas as pd


def _extract_names(series):

    return series.apply(
        lambda x: "|".join(item["name"] for item in x)
        if isinstance(x, list) else np.nan
    )


def clean_movies(df):

    df = df.copy()

    # ------------------------------------------------------------------
    # Drop irrelevant columns
    # ------------------------------------------------------------------
    df = df.drop(
        columns=['adult', 'imdb_id', 'original_title', 'video', 'homepage'],
        errors='ignore'
    )

    # ------------------------------------------------------------------
    # Extract collection name
    # ------------------------------------------------------------------
    df['belongs_to_collection'] = df['belongs_to_collection'].apply(
        lambda x: x['name'] if isinstance(x, dict) else np.nan
    )

    # ------------------------------------------------------------------
    # Flatten JSON-like columns
    # ------------------------------------------------------------------
    json_columns = [
        'genres',
        'production_countries',
        'production_companies',
        'spoken_languages'
    ]

    for col in json_columns:
        df[col] = _extract_names(df[col])

    # ------------------------------------------------------------------
    # Convert data types
    # ------------------------------------------------------------------
    numeric_columns = [
        'budget', 'revenue', 'runtime',
        'vote_count', 'vote_average', 'popularity', 'id'
    ]

    df[numeric_columns] = df[numeric_columns].apply(
        pd.to_numeric, errors='coerce'
    )

    df['release_date'] = pd.to_datetime(
        df['release_date'], errors='coerce'
    )

    # ------------------------------------------------------------------
    # Handle unrealistic and missing values
    # ------------------------------------------------------------------
    df[['budget', 'revenue', 'runtime']] = (
        df[['budget', 'revenue', 'runtime']].replace(0, np.nan)
    )

    # vote_count = 0 to rating is unreliable
    df.loc[df['vote_count'] == 0, 'vote_average'] = np.nan

    df['overview'] = df['overview'].replace('No Data', np.nan)
    df['tagline'] = df['tagline'].replace('No Data', np.nan)

    # ------------------------------------------------------------------
    # Convert budget and revenue to million USD
    # ------------------------------------------------------------------
    df['budget_musd'] = df['budget'] / 1_000_000
    df['revenue_musd'] = df['revenue'] / 1_000_000

    # ------------------------------------------------------------------
    # Remove duplicates and invalid rows
    # ------------------------------------------------------------------
    df = df.drop_duplicates(subset='id')
    df = df.dropna(subset=['id', 'title'])

    # ------------------------------------------------------------------
    # Keep rows with sufficient information
    # ------------------------------------------------------------------
    df = df[df.notna().sum(axis=1) >= 10]

    # ------------------------------------------------------------------
    # Keep only released movies
    # ------------------------------------------------------------------
    if 'status' in df.columns:
        df = df[df['status'] == 'Released']
        df = df.drop(columns='status')

    # ------------------------------------------------------------------
    # Reorder columns
    # ------------------------------------------------------------------
    final_columns = [
        'id', 'title', 'tagline', 'release_date', 'genres',
        'belongs_to_collection', 'original_language',
        'budget_musd', 'revenue_musd',
        'production_companies', 'production_countries',
        'vote_count', 'vote_average', 'popularity', 'runtime',
        'overview', 'spoken_languages', 'poster_path',
        'cast', 'cast_size', 'director', 'crew_size'
    ]

    # Keep only columns that exist
    final_columns = [col for col in final_columns if col in df.columns]
    df = df[final_columns]

    return df.reset_index(drop=True)