# -*- coding: utf-8 -*-
"""credits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bIQdBbAgYLG4ptyZjsXBJjdSclSFtez7
"""

"""
This module retrieves cast and crew information for movies from the
TMDb Credits API endpoint.

Responsibilities:
- Fetch cast and crew data for each movie
- Extract actor names, director name, and crew size
- Return a structured Pandas DataFrame ready for merging

"""

import requests
import pandas as pd

# TMDb credits endpoint
CREDITS_URL = "https://api.themoviedb.org/3/movie/{}/credits"


def fetch_credits(movie_ids, api_key):

    records = []

    for movie_id in movie_ids:
        if movie_id == 0:
            continue

        response = requests.get(
            CREDITS_URL.format(movie_id),
            params={"api_key": api_key}
        )

        # Skip failed API responses
        if response.status_code != 200:
            continue

        data = response.json()

        # Extract cast
        cast_list = data.get("cast", [])
        cast_names = [member["name"] for member in cast_list]

        # Extract crew
        crew_list = data.get("crew", [])
        directors = [
            member["name"] for member in crew_list
            if member.get("job") == "Director"
        ]

        records.append({
            "id": movie_id,
            "cast": "|".join(cast_names),
            "cast_size": len(cast_names),
            "director": directors[0] if directors else None,
            "crew_size": len(crew_list)
        })

    return pd.DataFrame(records)