# -*- coding: utf-8 -*-
"""features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EI3tMaP5e7beH-WBujgv3x5-ybhHkCMo
"""

"""
This module performs feature engineering and KPI (Key Performance Indicator)
calculations on the cleaned TMDb movie dataset.

Responsibilities:
- Compute financial KPIs such as profit and ROI
- Create derived analytical features
- Classify movies as franchise or standalone
- Ensure vectorized operations for scalability
"""

import numpy as np
import pandas as pd


def add_kpis(df):

    df = df.copy()

    # --------------------------------------------------------------
    # Profit (Revenue - Budget)
    # --------------------------------------------------------------
    df['profit_musd'] = df['revenue_musd'] - df['budget_musd']

    # --------------------------------------------------------------
    # Return on Investment (ROI)
    # --------------------------------------------------------------
    df['roi'] = df['revenue_musd'] / df['budget_musd']

    # Replace infinite values (division by zero) with NaN
    df.replace([np.inf, -np.inf], np.nan, inplace=True)

    # --------------------------------------------------------------
    # Franchise Classification
    # --------------------------------------------------------------
    df['is_franchise'] = df['belongs_to_collection'].notna()

    return df

