# -*- coding: utf-8 -*-
"""tmdb_movie_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DQfxmCaXGJL5TedOwF_bpf0TsBp4wWC4

# TMDb Movie Data Analysis using Pandas and APIs

## Project Overview

This notebook contains an end-to-end movie data analysis pipeline using
The Movie Database (TMDb) API. The workflow includes:

1. API data extraction
2. Data cleaning and preprocessing
3. Feature engineering and KPI analysis
4. Exploratory data analysis (EDA)
5. Advanced filtering and ranking
6. Franchise and director performance analysis
7. Data visualization and insights

All core logic is implemented in modular Python scripts (`.py` files) located
in the `functions/` directory. The notebook only coordinates function calls, following
professional and scalable data analytics practices.

## Project Setup

This notebook is designed to run in **Google Colab**.
All project logic is stored in Python modules under the `functions/` directory.

## Import Libraries and Project Modules

We import the required Python libraries and custom project modules.
The notebook does not contain processing logic; all operations are
performed through imported functions.
"""

import os

os.makedirs("functions", exist_ok=True)

import pandas as pd
import numpy as np

from functions.api import fetch_movies
from functions.credits import fetch_credits
from functions.cleaning import clean_movies
from functions.features import add_kpis
from functions.analysis import (
    rank_movies,
    search_bruce_willis_scifi_action,
    search_uma_thurman_tarantino,
    franchise_summary,
    top_franchises,
    top_directors
)
from functions.visualization import (
    plot_budget_vs_revenue,
    plot_roi_by_genre,
    plot_popularity_vs_rating,
    plot_yearly_revenue,
    plot_franchise_vs_standalone
)

"""## API Configuration

Define the TMDb API key and the list of movie IDs provided in the project
specification.

"""

API_KEY = "1a66cf9f283cad8d30e13096de0af285"


movie_ids = [
    0, 299534, 19995, 140607, 299536, 597, 135397,
    420818, 24428, 168259, 99861, 284054, 12445,
    181808, 330457, 351286, 109445, 321612, 260513
]

"""## Step 1: Fetch Movie Data from TMDb API

Movie metadata is retrieved using the TMDb REST API. Each movie ID uniquely
identifies a movie in the database.

"""

df_movies = fetch_movies(movie_ids, API_KEY)
df_movies.head()

"""## Fetch Cast, Director, and Crew Information

Cast and director information is retrieved from a separate TMDb credits
endpoint and merged with the main movie dataset.

"""

credits_df = fetch_credits(movie_ids, API_KEY)
df_movies = df_movies.merge(credits_df, on="id", how="left")
df_movies.head()

"""## Step 2: Data Cleaning and Preprocessing

The raw dataset contains nested JSON structures, missing values,
and unrealistic entries. This step standardizes the dataset and
prepares it for analysis.

"""

df_clean = clean_movies(df_movies)
df_clean.info()

"""## Exploratory Data Analysis (EDA)

Value distributions are inspected to detect anomalies and understand
the structure of extracted categorical fields.

"""

df_clean['genres'].value_counts().head()

df_clean['spoken_languages'].value_counts().head()

df_clean['production_countries'].value_counts().head()

"""## Step 3: Feature Engineering and KPI Calculation

Key performance indicators such as profit, ROI, and franchise classification
are added using vectorized operations.

"""

df_kpi = add_kpis(df_clean)
df_kpi[['title', 'budget_musd', 'revenue_musd', 'profit_musd', 'roi']].head()

"""## KPI Ranking Analysis

Movies are ranked based on financial, popularity, and rating metrics.

"""

rank_movies(df_kpi, 'revenue_musd')

rank_movies(df_kpi, 'profit_musd')

rank_movies(df_kpi, 'roi', min_budget=10)

rank_movies(df_kpi, 'vote_average', min_votes=10)

"""## Advanced Filtering & Search Queries

Specific actor- and director-based questions are answered using
advanced filtering.

"""

search_bruce_willis_scifi_action(df_kpi)

search_uma_thurman_tarantino(df_kpi)

"""## Franchise vs Standalone Movie Performance

This section compares franchise and standalone movies using key
performance indicators.

"""

franchise_summary(df_kpi)

"""## Most Successful Movie Franchises

"""

top_franchises(df_kpi)

"""## Most Successful Directors

"""

top_directors(df_kpi)

"""## Step 4: Data Visualization

Visualizations are used to communicate insights and trends identified
during the analysis phase.

## 1️⃣ Revenue vs Budget
"""

plot_budget_vs_revenue(df_kpi)

"""###  What the plot shows

* X-axis: **Movie Budget (Million USD)**
* Y-axis: **Movie Revenue (Million USD)**
* Each dot represents one movie
* The line shows the **overall trend**

### Interpretation

* There is a **positive relationship** between budget and revenue.
* Movies with **higher budgets generally earn higher revenues**.
* However, the spread of points shows that **high budget does not guarantee high revenue**.
* Some mid-budget movies perform very well, while some expensive movies underperform.



> This plot shows that while increasing budget often leads to higher revenue, profitability depends on other factors such as audience reception, genre, and marketing.

2️⃣ Top 10 Genres by Mean ROI
"""

plot_roi_by_genre(df_kpi)

"""###  What the plot shows

* X-axis: **Movie Genres**
* Y-axis: **Mean Return on Investment (ROI)**
* Bars represent average ROI per genre

### Interpretation

* **Fantasy, Comedy, and Romance** have the highest average ROI.
* Genres like **Action and Science Fiction**, despite high budgets, show **lower average ROI**.
* This suggests that **lower-cost genres can be more profitable**.

> This visualization highlights that genres with moderate production costs often achieve higher returns compared to big-budget genres.

## 3️⃣ Popularity vs Rating
"""

plot_popularity_vs_rating(df_kpi)

"""###  What the plot shows

* X-axis: **Popularity score**
* Y-axis: **Average user rating**
* Each dot represents one movie

###  Interpretation

* There is **no strong linear relationship** between popularity and rating.
* Some very popular movies have average ratings.
* Some less popular movies have high ratings.


> Popularity measures visibility and audience reach, while ratings reflect viewer satisfaction. These two metrics do not always move together.

## 4️⃣ Yearly Box Office Revenue Trends
"""

plot_yearly_revenue(df_kpi)

"""###  What the plot shows

* X-axis: **Release Year**
* Y-axis: **Total Revenue per Year (Million USD)**

###  Interpretation

* Box office revenue fluctuates significantly across years.
* Some years show sharp peaks due to **blockbuster releases**.
* Other years show dips, likely due to fewer high-grossing films.

> This trend shows how the movie industry is influenced by the release timing of major films rather than steady year-to-year growth.

## 5️⃣ Franchise vs Standalone Movie Revenue
"""

plot_franchise_vs_standalone(df_kpi)

"""###  What the plot shows

* Comparison of **mean revenue** between:

  * Standalone movies
  * Franchise movies

###  Interpretation

* Franchise movies generate **slightly higher or comparable average revenue**.
* However, the difference is not extreme.
* This indicates that **standalone movies can still be financially successful**.


> While franchises benefit from established audiences, standalone films can compete successfully when well executed.

> The visualizations collectively show that movie success is multi-dimensional. Budget, genre, popularity, and franchise status all contribute to performance, but none alone guarantees success.

## Conclusion

This project demonstrates a complete movie data analysis pipeline using
real-world data from the TMDb API. By combining modular Python scripts,
robust data cleaning, KPI analysis, advanced filtering, and visualization,
the project highlights how data-driven approaches can uncover insights
into movie performance beyond simple budget and revenue comparisons.

The modular design ensures scalability, maintainability, and alignment
with professional data analytics and data engineering best practices.
"""

