# -*- coding: utf-8 -*-
"""visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Z6fkItaVKXZkE4zhoQYRWqAwhWZbOVK
"""

"""
This module contains visualization functions used to present insights
from the TMDb movie dataset.

Responsibilities:
- Visualize financial trends and relationships
- Compare profitability across genres
- Analyze popularity vs rating
- Show time-based box office trends
- Compare franchise vs standalone performance

"""

import matplotlib.pyplot as plt
import numpy as np


# ----------------------------------------------------------------------
# 1. Revenue vs Budget
# ----------------------------------------------------------------------
def plot_budget_vs_revenue(df):
    """
    Visualize the relationship between movie budget and revenue.
    """
    plt.figure(figsize=(8, 6))

    plt.scatter(
        df['budget_musd'],
        df['revenue_musd'],
        alpha=0.7
    )

    # Trend line
    z = np.polyfit(df['budget_musd'], df['revenue_musd'], 1)
    p = np.poly1d(z)
    plt.plot(df['budget_musd'], p(df['budget_musd']))

    plt.xlabel("Budget (Million USD)")
    plt.ylabel("Revenue (Million USD)")
    plt.title("Revenue vs Budget")
    plt.tight_layout()
    plt.show()


# ----------------------------------------------------------------------
# 2. ROI Distribution by Genre
# ----------------------------------------------------------------------
def plot_roi_by_genre(df, top_n=10):
    """
    Visualize mean ROI by genre.
    """
    genre_roi = (
        df.dropna(subset=['genres', 'roi'])
        .assign(genres=df['genres'].str.split('|'))
        .explode('genres')
        .groupby('genres')['roi']
        .mean()
        .sort_values(ascending=False)
        .head(top_n)
    )

    plt.figure(figsize=(9, 6))
    genre_roi.plot(kind='bar')

    plt.ylabel("Mean ROI")
    plt.title(f"Top {top_n} Genres by Mean ROI")
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()


# ----------------------------------------------------------------------
# 3. Popularity vs Rating
# ----------------------------------------------------------------------
def plot_popularity_vs_rating(df):
    """
    Visualize the relationship between popularity and user rating.
    """
    plt.figure(figsize=(8, 6))

    plt.scatter(
        df['popularity'],
        df['vote_average'],
        alpha=0.7
    )

    plt.xlabel("Popularity")
    plt.ylabel("Average Rating")
    plt.title("Popularity vs Rating")
    plt.tight_layout()
    plt.show()


# ----------------------------------------------------------------------
# 4. Yearly Box Office Trends
# ----------------------------------------------------------------------
def plot_yearly_revenue(df):
    """
    Visualize yearly trends in total box office revenue.
    """
    df = df.copy()
    df['release_year'] = df['release_date'].dt.year

    yearly_revenue = (
        df.dropna(subset=['release_year', 'revenue_musd'])
        .groupby('release_year')['revenue_musd']
        .sum()
        .sort_index()
    )

    plt.figure(figsize=(10, 6))
    plt.plot(yearly_revenue.index, yearly_revenue.values, marker='o')

    plt.xlabel("Release Year")
    plt.ylabel("Total Revenue (Million USD)")
    plt.title("Yearly Box Office Revenue Trends")
    plt.tight_layout()
    plt.show()


# ----------------------------------------------------------------------
# 5. Franchise vs Standalone Comparison
# ----------------------------------------------------------------------
def plot_franchise_vs_standalone(df):
    """
    Compare mean revenue between franchise and standalone movies.
    """
    comparison = (
        df.groupby('is_franchise')['revenue_musd']
        .mean()
    )

    plt.figure(figsize=(6, 5))
    comparison.plot(kind='bar')

    plt.xticks([0, 1], ['Standalone', 'Franchise'], rotation=0)
    plt.ylabel("Mean Revenue (Million USD)")
    plt.title("Franchise vs Standalone Movie Revenue")
    plt.tight_layout()
    plt.show()

